# "org" ensures this Service is used with the correct Serverless Framework Access Key.
# org: sethmiller
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
# app: state-parks-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: state-parks-api

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: 20201221
  region: us-west-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ParksTable, Arn]

functions:
  createPark:
    handler: src/handlers.createPark
    events:
      - httpApi:
          path: /park
          method: post
  getPark:
    handler: src/handlers.getPark
    events:
      - httpApi:
          path: /park/{id}
          method: get
  updatePark:
    handler: src/handlers.updatePark
    events:
      - httpApi:
          path: /park/{id}
          method: put
  deletePark:
    handler: src/handlers.deletePark
    events:
      - httpApi:
          path: /park/{id}
          method: delete
  listPark:
    handler: src/handlers.listPark
    events:
      - httpApi:
          path: /parks
          method: get

plugins: -serverless-plugin-typescript

resources:
  Resources:
    ParksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: parkId
            AttributeType: S
        KeySchema:
          - AttributeName: parkId
            KeyType: HASH
        TableName: ParksTable
